version: '3.8'
services:
  mongodb:
    image: mongo:4.4.3-bionic
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
  flaskapp:
    image: flaskapp
    container_name: flaskapp-container_1
    build:
      context: .
      dockerfile: ./Dockerfile_devel
    ports:
      - "5000:5000"
    environment:
      - DB=mongodb://mongodb:27017/tasks
      - PORT=5000
    depends_on:
      - mongodb
