name: Test opencms service

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest
    
    services:
    
      mongodb:
        image: mongo:4.4.3-bionic
        options: >-
                --health-cmd mongo
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
        ports:
          - 20017:20017
        
      flaskapp:
        image: ghcr.io/udloficial/flaskapp:2_action_crear_imatge
        ports:
          - "5000:5000"
        env:
          - DB=mongodb://mongodb:27017/tasks
          - PORT=5000   
   
    steps:
      - uses: actions/checkout@v1
      
      - name: Verify Flaskapp connection
        env:
          PORT: ${{ job.services.flaskapp.ports[5000] }}
        run: |
          while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:$PORT/)" != "200" ]]; do sleep 1; done
          
      - name: Run k6 test
        env:
          PORT: 5000
          HOST: flaskapp
        uses: grafana/k6-action@v0.2.0
        with:
          filename: test.js
          flags: -e PORT=$PORT -e HOST=$HOST
